# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2017
  configuration: AppVeyor
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '2.3.1.{build}'
    assembly_file_version: '2.3.1.{build}'
    assembly_informational_version: '2.3.1.{build}'
  environment:
    RestorePackages: false
  before_build:
  - ps: .paket\paket.exe install
  build:
    project: MaterialDesignToolkit.Wpf.sln
    verbosity: minimal
  after_build:
  - ps: nuget pack MaterialDesignThemes.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  artifacts:
  - path: '**\MaterialDesignThemes.*.nupkg'
  - path: bin\**\*.*

  version: 2.3.1-ci{build}
  deploy:
  - provider: NuGet
    api_key:
      secure: B+WIdbRYr/rJo1QMeDwNen2xcj4RTu1d8AZiA03kb8wsWZVQxt5OgsWRacmEjWRd

# configuration for release branch
-
  branches:
    only:
      - release

  os: Visual Studio 2017
  configuration: AppVeyor
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    RestorePackages: false    
  before_build:
  - ps: .paket\paket.exe install
  build:
    project: MaterialDesignToolkit.Wpf.sln
    verbosity: minimal
  after_build:
  - ps: nuget pack MaterialDesignThemes.nuspec -Version $env:APPVEYOR_BUILD_VERSION
  artifacts:
  - path: '**\MaterialDesignThemes.*.nupkg'
  - path: bin\**\*.*

  version: 2.3.1.{build}