CREATE TABLE Coachs
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Firstname VARCHAR(64),
	Lastname VARCHAR(64)
);

CREATE TABLE Stadiums
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(64),
	City VARCHAR(64)
);

CREATE TABLE Teams
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(64),
	Id_Coach INT FOREIGN KEY
		REFERENCES Coachs (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	Id_Stadium INT FOREIGN KEY
		REFERENCES Stadiums (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
);

CREATE TABLE Roles
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(64)
);

CREATE TABLE Tours
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(64)
);

CREATE TABLE Games
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Id_HomeTeam INT FOREIGN KEY
		REFERENCES Teams (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	Id_GuestTeam INT FOREIGN KEY
		REFERENCES Teams (Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	Id_Stadium INT FOREIGN KEY
		REFERENCES Stadiums (Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	Id_Tour INT FOREIGN KEY
		REFERENCES Tours (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE Players
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Firstname VARCHAR(64),
	Lastname VARCHAR (64),
	Id_Position INT FOREIGN KEY
		REFERENCES Roles (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	Id_Team INT FOREIGN KEY
		REFERENCES Teams (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE Goals
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Id_Game INT FOREIGN KEY
		REFERENCES Games (Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	Id_Player INT FOREIGN KEY
		REFERENCES Players (Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);